platform :ios, '9.0'
use_frameworks!

target 'Tally' do
    pod 'SDWebImage'
    pod 'TTTAttributedLabel'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Google/CloudMessaging'
    pod 'SSKeychain'
    pod 'Stripe'
    pod 'ActionSheetPicker-3.0'
end
